apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource-tree-handler.fullname" . }}
  labels:
    {{- include "resource-tree-handler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 'composition.krateo.io'
  resources:
  - '*'
  verbs:
  - patch
  - update
