apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource-tree-handler.fullname" . }}
  labels:
  {{- include "resource-tree-handler.labels" . | nindent 4 }}
data:
  RESOURCE_TREE_HANDLER_API_PORT: "{{ .Values.service.port }}"
  DEBUG_LEVEL: "{{ .Values.env.debug.level }}"
  URL_SSE: "{{ .Values.env.sse.url }}"
